[package]
name = "sts2-mcp"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
tokio = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }

[[bin]]
name = "sts2-mcp-mock"
path = "src/bin/sts2-mcp-mock.rs"

[dev-dependencies]
sts2-core = { workspace = true }
